// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-uAF_Z7ZTukCzOlfM6glZ1fTIznXNWWI',
    appId: '1:394732166060:android:3ef985d34a553f99c1b809',
    messagingSenderId: '394732166060',
    projectId: 'tudo-list-provider',
    storageBucket: 'tudo-list-provider.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBglCvBXrHKfatvMSD8qnkaXSSybHYIeRY',
    appId: '1:394732166060:ios:e8d969a09c69a297c1b809',
    messagingSenderId: '394732166060',
    projectId: 'tudo-list-provider',
    storageBucket: 'tudo-list-provider.appspot.com',
    androidClientId: '394732166060-ac2vq5h6djpgjes884c054vcndh6oc1n.apps.googleusercontent.com',
    iosClientId: '394732166060-0kcosvnlqasn2hnjnbglh7ajstecnjvj.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );
}
